### ISSUE TITLE
Crashlytics warning

### ISSUE THREAD

**Issue by artemnovichkov** [Building42/Specs#19]
I added Fabric and Crashlytics via you specs and use fastlane for builds. I see this log message during `crashlytics` lane:
```
Crashlytics has moved the submit binary outside of Crashlytics.framework directory as of 3.4.1. Please change :crashlytics_path to `<PODS_ROOT>/Crashlytics/submit\
```
Have you seen this message?

**Comment by yvbeek** [comment]
It seems that the binaries are no longer in the framework, but stored outside of it.
There is a Fastlane issue about this: https://github.com/fastlane/fastlane/issues/12820

Have you tried the latest Crashlytics + the latest Fastlane?
I hope that the Fabric / Crashlytics team isn't breaking non-CocoaPods setups.

**Comment by artemnovichkov** [comment]
I'm using:
fastlane 2.102.0
Fabric 1.7.9
Crashlytics 3.10.5
Will try to update the dependencies, thank you!
