### ISSUE TITLE
more besides fabric stuff?

### ISSUE THREAD

**Issue by pvinis** [Building42/Specs#22]
could i make a pr to add some extra stuff?
like google analytics, or bvlineargradient and other things?
or is it focused on fabric only?

thanks for making this repo :D

**Comment by yvbeek** [comment]
@pvinis Hi, yes PRs for other libraries are very welcome!

Please make sure that the library actually requires a JSON. If the library's source is available on GitHub and their Xcode project contains public schemes, then a JSON often isn't required.

- [ ] Add the iOS, MacOS and tvOS specs to the `Specs/Carthage` folder
- [ ] Update the README with information on the framework
- [ ] Test the JSON on your clone of the repo
