### ISSUE TITLE
upload-symbols tool is absent, but in cocoapods archive it exists

### ISSUE THREAD

**Issue by Igor-Palaguta** [Building42/Specs#23]
Hello guys,

Thanks for adding support for Carthage!

But unfortunately fastlane upload_symbols_to_crashlytics does not work. As it expects `upload-symbols` tool, that is absent in zips.

[Cocoapods](https://github.com/CocoaPods/Specs/blob/master/Specs/0/a/c/Fabric/1.7.13/Fabric.podspec.json) uses this zip https://kit-downloads.fabric.io/cocoapods/fabric/1.7.13/fabric.zip, but in your file we can see: https://kit-downloads.fabric.io/ios/io.fabric.sdk.ios/1.7.13/io.fabric.sdk.ios-default.zip

And really in your these *.default.zip this upload-symbols tool is missing

**Comment by yvbeek** [comment]
Hi Igor, thank you for sharing this.

I see that [fabric.zip](https://kit-downloads.fabric.io/cocoapods/fabric/1.7.13/fabric.zip) contains the macOS, iOS and tvOS frameworks. Perhaps the best thing to do for me is to create a `Universal` folder in the `Specs/Carthage` folder and place a JSON linking to that zip in there?

Does Crashlytics have the same problem with Fastlane?

Please let me know what you think.

**Comment by yvbeek** [comment]
@Igor-Palaguta ?

**Comment by Igor-Palaguta** [comment]
Hello @Zyphrax ,

It would be great if we have also archives like in Cocoapods.

Thanks

**Comment by yvbeek** [comment]
@Igor-Palaguta Could you test this in your Cartfile? And see if it works with Fastlane?

```
binary "https://raw.githubusercontent.com/Building42/Specs/universal/Carthage/Universal/Fabric.json"
```

This is a temporary link. I'll replace it later on if this works.

**Comment by Igor-Palaguta** [comment]
Thanks, let me check

**Comment by Igor-Palaguta** [comment]
Unfortunately it does not work. Looks like Carthage is too smart and it downloads just iOS folder for iOS. And does not download whole folder with upload-symbols tool

**Comment by yvbeek** [comment]
Hmmm that's unfortunate.

The Fabric app also contains the `upload-symbols` tool, it probably doesn't change that often. Can you link to that using Fastlane? Or maybe extract the tool to a Scripts folder in your repository.

The `upload_symbols_to_crashlytics` command has an argument `binary_path`, you can use that to override the path of the `upload-symbols` tool.

It is frustrating that Fabric clings so heavily to CocoaPods.

**Comment by Igor-Palaguta** [comment]
Yes, looks like to add this tool inside repository is the one variant with Carthage.

Thank you!
