### ISSUE TITLE
must be a popular framework?

### ISSUE THREAD

**Issue by Ricardo1980** [Building42/Specs#28]
Hello,
I am working with  a library called Nabto (internet of things, it is used to create tunnels).
Can I add that one?
Evidently, it is not popular.
Thanks.

**Comment by yvbeek** [comment]
Hi @Ricardo1980 sure!

Feel free to drop me a pull request for Nabto. In your pull request please add:
- a section to the [README](https://github.com/Building42/Specs/blob/master/README.md) for Nabto below Crashlytics
- JSON files for the architectures in the [Carthage](https://github.com/Building42/Specs/tree/master/Carthage) subfolders
